=== asyncapi/spec-json-schemas/examples/schemas/json/draft-07-core-schema-meta-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://json-schema.org/draft-07/schema#",
  "title": "Core schema meta-schema",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "nonNegativeInteger": {
      "type": "integer",
      "minimum": 0
    },
    "nonNegativeIntegerDefault0": {
      "allOf": [
        {
          "$ref": "#/definitions/nonNegativeInteger"
        },
        {
          "default": 0
        }
      ]
    },
    "simpleTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "default": []
    }
  },
  "type": [
    "object",
    "boolean"
  ],
  "properties": {
    "$id": {
      "type": "string",
      "format": "uri-reference"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference"
    },
    "$comment": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": true,
    "readOnly": {
      "type": "boolean",
      "default": false
    },
    "writeOnly": {
      "type": "boolean",
      "default": false
    },
    "examples": {
      "type": "array",
      "items": true
    },
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "number"
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "number"
    },
    "maxLength": {
      "$ref": "#/definitions/nonNegativeInteger"
    },
    "minLength": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0"
    },
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "additionalItems": {
      "$ref": "#"
    },
    "items": {
      "anyOf": [
        {
          "$ref": "#"
        },
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "default": true
    },
    "maxItems": {
      "$ref": "#/definitions/nonNegativeInteger"
    },
    "minItems": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0"
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "contains": {
      "$ref": "#"
    },
    "maxProperties": {
      "$ref": "#/definitions/nonNegativeInteger"
    },
    "minProperties": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0"
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    },
    "additionalProperties": {
      "$ref": "#"
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "propertyNames": {
        "format": "regex"
      },
      "default": {}
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "anyOf": [
          {
            "$ref": "#"
          },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      }
    },
    "propertyNames": {
      "$ref": "#"
    },
    "const": true,
    "enum": {
      "type": "array",
      "items": true,
      "minItems": 1,
      "uniqueItems": true
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "format": {
      "type": "string"
    },
    "contentMediaType": {
      "type": "string"
    },
    "contentEncoding": {
      "type": "string"
    },
    "if": {
      "$ref": "#"
    },
    "then": {
      "$ref": "#"
    },
    "else": {
      "$ref": "#"
    },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "not": {
      "$ref": "#"
    }
  },
  "default": true
}

=== asyncapi/spec-json-schemas/definitions/3.1.0/messages.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/3.1.0/messages.json",
  "description": "JSON objects describing the messages being consumed and produced by the API.",
  "type": "object",
  "additionalProperties": {
    "oneOf": [
      {
        "$ref": "http://asyncapi.com/definitions/3.1.0/Reference.json"
      },
      {
        "$ref": "http://asyncapi.com/definitions/3.1.0/messageObject.json"
      }
    ]
  }
}

=== asyncapi/spec-json-schemas/draft-07/schemas/v2/security/oauth2/oauth2Scopes.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8000/draft-07/schemas/v2/security/oauth2/oauth2Scopes.json",
  "title": "AsyncAPI v2 - OAuth2 Scopes",
  "description": "Scopes let you specify exactly what type of access you need. Scopes limit access for OAuth tokens. They do not grant any additional permission beyond that which the user already has",
  "examples": [
    {
      "write:pets": "modify pets in your account",
      "read:pets": "read your pets"
    }
  ],
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}

=== asyncapi/spec-json-schemas/draft-07/schemas/v2.2.0/channels/messages/messages.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8000/draft-07/schemas/v2.2.0/channels/messages/messages.json",
  "title": "AsyncAPI v2.2.0 - Channel Operation Messages Map",
  "description": "A key-value map where key is message ID and value is message representation",
  "type": "object",
  "examples": [
    {
      "userSignup": {
        "$ref": "#/components/messages/userSignup"
      }
    },
    {
      "userSignup": {
        "name": "UserSignup",
        "title": "User signup",
        "summary": "Action to sign a user up.",
        "description": "A longer description",
        "tags": [
          { "name": "user" },
          { "name": "signup" },
          { "name": "register" }
        ],
        "payload": {
          "$ref": "path/to/user-create.avsc#/UserCreate"
        }
      }
    }
  ],
  "additionalProperties": {
    "$ref": "http://localhost:8000/draft-07/schemas/v2.2.0/channels/messages/message.json"
  }
}

=== asyncapi/spec-json-schemas/draft-07/schemas/v2.5.0/channels/messages/messages.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8000/draft-07/schemas/v2.5.0/channels/messages/messages.json",
  "title": "AsyncAPI v2.5.0 - Channel Operation Messages Map",
  "description": "A key-value map where key is message ID and value is message representation",
  "type": "object",
  "additionalProperties": {
    "$ref": "http://localhost:8000/draft-07/schemas/v2.5.0/channels/messages/message.json"
  }
}

=== asyncapi/spec-json-schemas/definitions/2.4.0/parameters.json
{
  "type": "object",
  "additionalProperties": {
    "$ref": "http://asyncapi.com/definitions/2.4.0/parameter.json"
  },
  "description": "JSON objects describing re-usable channel parameters.",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/2.4.0/parameters.json"
}
