=== asyncapi/spec-json-schemas/examples/schemas/json/draft-07-core-schema-meta-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://json-schema.org/draft-07/schema#",
  "title": "Core schema meta-schema",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "nonNegativeInteger": {
      "type": "integer",
      "minimum": 0
    },
    "nonNegativeIntegerDefault0": {
      "allOf": [
        {
          "$ref": "#/definitions/nonNegativeInteger"
        },
        {
          "default": 0
        }
      ]
    },
    "simpleTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "default": []
    }
  },
  "type": [
    "object",
    "boolean"
  ],
  "properties": {
    "$id": {
      "type": "string",
      "format": "uri-reference"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference"
    },
    "$comment": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": true,
    "readOnly": {
      "type": "boolean",
      "default": false
    },
    "writeOnly": {
      "type": "boolean",
      "default": false
    },
    "examples": {
      "type": "array",
      "items": true
    },
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "number"
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "number"
    },
    "maxLength": {
      "$ref": "#/definitions/nonNegativeInteger"
    },
    "minLength": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0"
    },
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "additionalItems": {
      "$ref": "#"
    },
    "items": {
      "anyOf": [
        {
          "$ref": "#"
        },
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "default": true
    },
    "maxItems": {
      "$ref": "#/definitions/nonNegativeInteger"
    },
    "minItems": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0"
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "contains": {
      "$ref": "#"
    },
    "maxProperties": {
      "$ref": "#/definitions/nonNegativeInteger"
    },
    "minProperties": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0"
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    },
    "additionalProperties": {
      "$ref": "#"
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "propertyNames": {
        "format": "regex"
      },
      "default": {}
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "anyOf": [
          {
            "$ref": "#"
          },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      }
    },
    "propertyNames": {
      "$ref": "#"
    },
    "const": true,
    "enum": {
      "type": "array",
      "items": true,
      "minItems": 1,
      "uniqueItems": true
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "format": {
      "type": "string"
    },
    "contentMediaType": {
      "type": "string"
    },
    "contentEncoding": {
      "type": "string"
    },
    "if": {
      "$ref": "#"
    },
    "then": {
      "$ref": "#"
    },
    "else": {
      "$ref": "#"
    },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "not": {
      "$ref": "#"
    }
  },
  "default": true
}

=== asyncapi/spec-json-schemas/draft-07/schemas/v2.0.0-rc1/security/oauth2/oauth2Scopes.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8000/draft-07/schemas/v2.0.0-rc1/security/oauth2/oauth2Scopes.json",
  "title": "AsyncAPI v2.0.0-rc1 - OAuth2 Scopes",
  "description": "Scopes let you specify exactly what type of access you need. Scopes limit access for OAuth tokens. They do not grant any additional permission beyond that which the user already has",
  "type": "object",
  "examples": [
    {},
    {
      "write:pets": "modify pets in your account",
      "read:pets": "read your pets"
    }
  ],
  "additionalProperties": {
    "type": "string"
  }
}

=== asyncapi/spec-json-schemas/draft-07/schemas/v2/security/securitySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8000/draft-07/schemas/v2/security/securitySchema.json",
  "title": "AsyncAPI v2 - Authentication Variants",
  "description": "Contains information about available authentication variants",
  "examples": [
    {
      "type": "httpApiKey",
      "description": "httpApiKey",
      "name": "api_key",
      "in": "header"
    },
    {
      "type": "http",
      "description": "http",
      "scheme": "basic"
    },
    {
      "type": "http",
      "description": "http",
      "scheme": "bearer",
      "bearerFormat": "JWT"
    },
    {
      "type": "oauth2",
      "description": "oauth2",
      "flows": {
        "authorizationCode": {
          "authorizationUrl": "https://example.com/api/oauth/dialog",
          "tokenUrl": "https://example.com/api/oauth/token",
          "refreshUrl": "https://example.com/api/oauth/refresh",
          "scopes": {
            "write:pets": "modify pets in your account",
            "read:pets": "read your pets"
          }
        },
        "clientCredentials": {
          "tokenUrl": "https://example.com/api/oauth/token",
          "refreshUrl": "https://example.com/api/oauth/refresh",
          "scopes": {
            "write:pets": "modify pets in your account",
            "read:pets": "read your pets"
          }
        },
        "implicit": {
          "authorizationUrl": "https://example.com/api/oauth/dialog",
          "refreshUrl": "https://example.com/api/oauth/refresh",
          "scopes": {
            "write:pets": "modify pets in your account",
            "read:pets": "read your pets"
          }
        },
        "password": {
          "tokenUrl": "https://example.com/api/oauth/token",
          "refreshUrl": "https://example.com/api/oauth/refresh",
          "scopes": {
            "write:pets": "modify pets in your account",
            "read:pets": "read your pets"
          }
        }
      },
      "scopes": [ "write:pets", "read:pets" ]
    },
    {
      "type": "X509",
      "description": "X509"
    },
    {
      "type": "apiKey",
      "description": "apiKey",
      "in": "user"
    },
    {
      "type": "asymmetricEncryption",
      "description": "asymmetricEncryption"
    },
    {
      "type": "gssapi",
      "description": "gssapi"
    },
    {
      "type": "openIdConnect",
      "description": "openIdConnect",
      "openIdConnectUrl": "https://server.com/.well-known/openid-configuration"
    },
    {
      "type": "plain",
      "description": "plain"
    },
    {
      "type": "scramSha256",
      "description": "scramSha256"
    },
    {
      "type": "scramSha512",
      "description": "scramSha512"
    },
    {
      "type": "symmetricEncryption",
      "description": "symmetricEncryption"
    },
    {
      "type": "userPassword",
      "description": "userPassword"
    }
  ],
  "oneOf": [
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/userPassword.json"
    },
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/apiKey.json"
    },
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/X509.json"
    },
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/symmetricEncryption.json"
    },
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/asymmetricEncryption.json"
    },
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/http/httpSecuritySchema.json"
    },
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/oauth2/oauth2.json"
    },
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/openIdConnect.json"
    },
    {
      "$ref": "http://localhost:8000/draft-07/schemas/v2/security/sasl/saslSecuritySchema.json"
    }
  ]
}

=== asyncapi/spec-json-schemas/definitions/3.0.0/operationBindingsObject.json
{
  "type": "object",
  "description": "Map describing protocol-specific definitions for an operation.",
  "additionalProperties": false,
  "patternProperties": {
    "^x-[\\w\\d\\.\\x2d_]+$": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/specificationExtension.json"
    }
  },
  "properties": {
    "http": {
      "properties": {
        "bindingVersion": {
          "enum": ["0.2.0", "0.3.0"]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/http/0.3.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.2.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/http/0.2.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.3.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/http/0.3.0/operation.json"
          }
        }
      ]
    },
    "ws": {},
    "amqp": {
      "properties": {
        "bindingVersion": {
          "enum": ["0.3.0"]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/amqp/0.3.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.3.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/amqp/0.3.0/operation.json"
          }
        }
      ]
    },
    "amqp1": {},
    "mqtt": {
      "properties": {
        "bindingVersion": {
          "enum": ["0.2.0"]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/mqtt/0.2.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.2.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/mqtt/0.2.0/operation.json"
          }
        }
      ]
    },
    "kafka": {
      "properties": {
        "bindingVersion": {
          "enum": ["0.5.0", "0.4.0", "0.3.0"]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/kafka/0.5.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.5.0"
              }
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/kafka/0.5.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.4.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/kafka/0.4.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.3.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/kafka/0.3.0/operation.json"
          }
        }
      ]
    },
    "anypointmq": {},
    "nats": {
      "properties": {
        "bindingVersion": {
          "enum": ["0.1.0"]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/nats/0.1.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.1.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/nats/0.1.0/operation.json"
          }
        }
      ]
    },
    "jms": {},
    "sns": {
      "properties": {
        "bindingVersion": {
          "enum": ["0.1.0"]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/sns/0.1.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.1.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/sns/0.1.0/operation.json"
          }
        }
      ]
    },
    "sqs": {
      "properties": {
        "bindingVersion": {
          "enum": ["0.2.0"]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/sqs/0.2.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.2.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/sqs/0.2.0/operation.json"
          }
        }
      ]
    },
    "stomp": {},
    "redis": {
      "properties": {
        "bindingVersion": {
          "enum": [
            "0.1.0",
            "0.2.0"
          ]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/redis/0.2.0/operation.json"
          }
        },
        {
          "if": {
            "required": [
              "bindingVersion"
            ],
            "properties": {
              "bindingVersion": {
                "const": "0.2.0"
              }
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/redis/0.2.0/operation.json"
          }
        }
      ]
    },
    "ibmmq": {},
    "solace": {
      "properties": {
        "bindingVersion": {
          "enum": ["0.4.0", "0.3.0", "0.2.0"]
        }
      },
      "allOf": [
        {
          "description": "If no bindingVersion specified, use the latest binding",
          "if": {
            "not": {
              "required": [
                "bindingVersion"
              ]
            }
          },
          "then": {
            "$ref": "http://asyncapi.com/bindings/solace/0.4.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.4.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/solace/0.4.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.3.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/solace/0.3.0/operation.json"
          }
        },
        {
          "if": {
            "required": [ "bindingVersion" ],
            "properties": {
              "bindingVersion": {
                "const": "0.2.0"
              }
            }
          }, 
          "then": {
            "$ref": "http://asyncapi.com/bindings/solace/0.2.0/operation.json"
          }
        }
      ]
    },
    "googlepubsub": {}
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/3.0.0/operationBindingsObject.json"
}

=== asyncapi/spec-json-schemas/draft-07/schemas/v2/securityRequirements.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8000/draft-07/schemas/v2/securityRequirements.json",
  "title": "AsyncAPI v2 - Operation Security Requirements",
  "description": "Lists of the required security schemes that can be used to execute an operation",
  "examples": [
    {
      "petstore_auth": [ "write:pets", "read:pets" ]
    }
  ],
  "type": "object",
  "additionalProperties": {
    "type": "array",
    "uniqueItems": true,
    "items": {
      "type": "string"
    }
  }
}

=== asyncapi/spec-json-schemas/draft-07/schemas/v2.1.0/servers/serverVariables.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8080/draft-07/schemas/v2.1.0/servers/serverVariables.json",
  "title": "AsyncAPI v2.1.0 - Server Variables Map",
  "description": "A key-value map where key is variable ID and value is variable representation",
  "examples": [
    {
      "port": {
        "enum": [ "8883", "8884" ],
        "default": "8883",
        "description": "Ports application listening for",
        "examples": [ "8883", "8884" ]
      }
    }
  ],
  "type": "object",
  "additionalProperties": {
    "$ref": "http://localhost:8080/draft-07/schemas/v2.1.0/servers/serverVariable.json"
  }
}

=== asyncapi/spec-json-schemas/definitions/3.1.0/channelMessages.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/3.1.0/channelMessages.json",
  "description": "A map of the messages that will be sent to this channel by any application at any time. **Every message sent to this channel MUST be valid against one, and only one, of the message objects defined in this map.**",
  "type": "object",
  "additionalProperties": {
    "oneOf": [
      {
        "$ref": "http://asyncapi.com/definitions/3.1.0/Reference.json"
      },
      {
        "$ref": "http://asyncapi.com/definitions/3.1.0/messageObject.json"
      }
    ]
  }
}

=== asyncapi/spec-json-schemas/definitions/2.0.0-rc2/parameters.json
{
  "type": "object",
  "additionalProperties": {
    "$ref": "http://asyncapi.com/definitions/2.0.0-rc2/parameter"
  },
  "description": "JSON objects describing re-usable channel parameters.",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/2.0.0-rc2/parameters"
}

=== asyncapi/spec-json-schemas/draft-07/schemas/v2.3.0/channels/channels.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8000/draft-07/schemas/v2.3.0/channels/channels.json",
  "title": "AsyncAPI v2.3.0 - Channels Map",
  "description": "A key-value map where key is channel ID and value is channel representation. Channel paths are relative to servers",
  "examples": [
    {
      "my-channel": {
        "$ref": "#/channels/my-channel"
      },
      "user/{userId}/sendMessage": {
        "description": "This channel is used to exchange messages about users signing up",
        "subscribe": {
          "operationId": "sendMessage",
          "summary": "Send message",
          "description": "Send message to remote server",
          "message": {
            "$ref": "#/components/schemas/sendMessage"
          }
        },
        "parameters": {
          "userId": {
            "description": "Id of the user",
            "schema": {
              "type": "string"
            },
            "location": "$message.payload#/user/id"
          }
        }
      }
    }
  ],
  "type": "object",
  "propertyNames": {
    "format": "uri-template",
    "minLength": 1
  },
  "additionalProperties": {
    "$ref": "http://localhost:8000/draft-07/schemas/v2.3.0/channels/channelItem.json"
  }
}
