=== asyncapi/spec-json-schemas/definitions/3.0.0/asyncapi.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/3.0.0/asyncapi.json",
  "title": "AsyncAPI 3.0.0 schema.",
  "type": "object",
  "required": [
    "asyncapi",
    "info"
  ],
  "properties": {
    "id": {
      "description": "A unique id representing the application.",
      "type": "string",
      "format": "uri"
    },
    "asyncapi": {
      "description": "The AsyncAPI specification version of this document.",
      "type": "string",
      "const": "3.0.0"
    },
    "channels": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/channels.json"
    },
    "components": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/components.json"
    },
    "defaultContentType": {
      "description": "Default content type to use when encoding/decoding a message's payload.",
      "type": "string"
    },
    "info": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/info.json"
    },
    "operations": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/operations.json"
    },
    "servers": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/servers.json"
    }
  },
  "patternProperties": {
    "^x-[\\w\\d\\.\\x2d_]+$": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/specificationExtension.json"
    }
  },
  "additionalProperties": false
}

=== asyncapi/spec-json-schemas/test/docs/3.0.0/streetlights-asyncapi.json
{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Account Service",
    "version": "1.0.0",
    "description": "This service is in charge of processing user signups"
  },
  "channels": {
    "AsyncAPI-UserSignedUpChannel": {
      "address": "user/signedup/{test_param}",
      "parameters": {
        "test_param": {
          "enum": [
            "test"
          ],
          "default": "test",
          "description": "Just a test description",
          "examples": [
            "test"
          ],
          "location": "$message.payload#",
          "x-custom-extension": "test"
        }
      },
      "messages": {
        "AsyncAPI-UserSignedUp": {
          "$ref": "#/components/messages/AsyncAPI-UserSignedUp"
        }
      }
    }
  },
  "operations": {
    "AsyncAPI-PublishUserSignedUp": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/AsyncAPI-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "bindingVersion": "0.2.0",
          "qos": 1
        },
        "kafka": {
          "bindingVersion": "0.3.0",
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    },
    "AsyncAPI-PublishUserSignedUpDefaultBinding": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/AsyncAPI-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "qos": 1
        },
        "kafka": {
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    }
  },
  "components": {
    "messages": {
      "AsyncAPI-UserSignedUp": {
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "type": "object",
            "properties": {
              "displayName": {
                "type": "string",
                "description": "Name of the user"
              },
              "email": {
                "type": "string",
                "format": "email",
                "description": "Email of the user"
              }
            },
            "externalDocs": {
              "url": "https://account-service/docs/UserSignedUp"
            },
            "deprecated": false
          }
        }
      },
      "AsyncAPI-UserSignedUpV2": {
        "payload": {
          "type": "object",
          "properties": {
            "displayName": {
              "type": "string",
              "description": "Name of the user"
            },
            "email": {
              "type": "string",
              "format": "email",
              "description": "Email of the user"
            }
          },
          "externalDocs": {
            "url": "https://account-service/docs/UserSignedUp"
          },
          "deprecated": false
        }
      },
      "AsyncAPI-UserSignedUpV3": {
        "payload": {
          "$ref": "external-schema.json"
        }
      }
    }
  }
}

=== asyncapi/spec-json-schemas/test/docs/3.0.0/streetlights-unknown.json
{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Account Service",
    "version": "1.0.0",
    "description": "This service is in charge of processing user signups"
  },
  "channels": {
    "Unknown-UserSignedUpChannel": {
      "address": "user/signedup/{test_param}",
      "parameters": {
        "test_param": {
          "enum": [
            "test"
          ],
          "default": "test",
          "description": "Just a test description",
          "examples": [
            "test"
          ],
          "location": "$message.payload#",
          "x-custom-extension": "test"
        }
      },
      "messages": {
        "UserSignedUp": {
          "$ref": "#/components/messages/Unknown-UserSignedUp"
        }
      }
    }
  },
  "operations": {
    "Unknown-PublishUserSignedUp": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/Unknown-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "bindingVersion": "0.2.0",
          "qos": 1
        },
        "kafka": {
          "bindingVersion": "0.3.0",
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    },
    "Unknown-PublishUserSignedUpDefaultBinding": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/Unknown-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "qos": 1
        },
        "kafka": {
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    }
  },
  "components": {
    "messages": {
      "Unknown-UserSignedUp": {
        "payload": {
          "schemaFormat": "unknown-schema-format",
          "schema": {
            "type": "object",
            "properties": {
              "displayName": {
                "type": "string",
                "description": "Name of the user"
              },
              "email": {
                "type": "string",
                "format": "email",
                "description": "Email of the user"
              }
            },
            "externalDocs": {
              "url": "https://account-service/docs/UserSignedUp"
            },
            "deprecated": false
          }
        }
      },
      "Unknown-UserSignedUpV2": {
        "payload": {
          "$ref": "external-schema.json"
        }
      }
    }
  }
}
